### ISSUE TITLE
DMS MVP - Mobile UI and selection mode

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-dms-demo#98]
### Tasks:
  - [x] Remove the checkboxes
  - [x] The icons should be the selectors instead of the checkboxes
     - [x] Entering selection mode: by tapping on the icons
     - [x] When we enter the selection mode, a floating bar appears ad the bottom, counting the elements and containing the batch actions available for the selected items
     - [x] One can select items from various places in the tree
     - [x] Exiting selection mode: either by removing everything from the selection, or selecting "Clear selection" from the context menu of the floating action bar
     - [x] If we are in selection mode, the floating action button and the individual three-dot action menu icons disappear
     - [x] In selection mode, only the batch actions apply, every individual action is disabled
